// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_withdrawal is a generated GoMock package.
package mock_withdrawal

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	withdrawal "github.com/nickzhog/gophermart/internal/service/withdrawal"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, w *withdrawal.Withdrawal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, w interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, w)
}

// FindByID mocks base method.
func (m *MockRepository) FindByID(ctx context.Context, id string) (withdrawal.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(withdrawal.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository)(nil).FindByID), ctx, id)
}

// FindForUser mocks base method.
func (m *MockRepository) FindForUser(ctx context.Context, usrID string) ([]withdrawal.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindForUser", ctx, usrID)
	ret0, _ := ret[0].([]withdrawal.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindForUser indicates an expected call of FindForUser.
func (mr *MockRepositoryMockRecorder) FindForUser(ctx, usrID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindForUser", reflect.TypeOf((*MockRepository)(nil).FindForUser), ctx, usrID)
}